version: '3.3'

services:

  snipe-db:
    container_name: snipe-db
    image: mysql
    env_file:
      - ./.env
    volumes:
      - $PWD/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"

  snipe-it:
    container_name: snipe-it
    image: snipe/snipe-it
    env_file:
      - ./.env
    # expose:
    # - "80"
    ports: 
      - 8888:80
    depends_on:
      - snipe-db
